config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'pages/info'

  get '/items/all', to: 'items#index_all'
  get '/items/current', to: 'items#index_current'
  get '/items/finished', to: 'items#index'

  get '/users/list', to: 'home#users'

  resources :workspaces do
    member do
      patch :move
    end
    get 'next', action: :next, controller: 'workspaces'
    get 'previous', action: :previous, controller: 'workspaces'
    resources :items do
      get 'next', action: :next, controller: 'items'
      get 'previous', action: :previous, controller: 'items'
      resources :dues
    end
  end

  root to: 'home#index'

end

app/models/workspace.rb
class Workspace < ApplicationRecord
    has_many :items, dependent: :destroy

    def next
        self.class.where("position > ?", position).order(:position).first
    end

    def previous
        self.class.where("position < ?", position).order(:position).last
    end

    acts_as_list
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
    helper_method :sort_column, :sort_direction
    before_action :set_workspace, only: [:show, :edit, :update, :destroy, :move]

    def move
        @workspace.insert_at(params[:position].to_i)
    end

    def index
      @workspaces = Workspace.all
      #@workspaces = Workspace.order(sort_column + " " + sort_direction)
    end

    def show
        @workspace = Workspace.find(params[:id])
    end

    def next
        @workspace = Workspace.find(params[:workspace_id])
        if @workspace == Workspace.order(:position).last
            flash[:alert] = "This is the last workspace!"
            redirect_to @workspace
        else
            redirect_to @workspace.next
        end
    end

    def previous
        @workspace = Workspace.find(params[:workspace_id])
        if @workspace == Workspace.all.order(:position).first
            flash[:alert] = "This is the first workspace!"
            redirect_to @workspace
        else
            redirect_to @workspace.previous
        end
    end
    
    def new
        @workspace = Workspace.new
        respond_to do |format|
            format.html
            format.js
        end
    end

    def edit
        @workspace = Workspace.find(params[:id])
        respond_to do |format|
            format.html
            format.js
        end
    end

    def create
        @workspace = Workspace.new(workspace_params)
        if Workspace.count == 0
            @workspace.position = 1
        else
            @workspace.position = Workspace.all.order(:position).last.position + 1
        end
        @workspace.save
        redirect_to @workspace
    end

    def update
        @workspace = Workspace.find(params[:id])

        if allow_to_update (@workspace.assign_attributes(workspace_params))
            @workspace.update(workspace_params)
            flash[:notice] = "Workspace successfully updated!"
            redirect_to @workspace
        else
            flash[:alert] = "The number of items exceeds the maximum workspace capacity!"
            redirect_to @workspace
        end
    end

    def allow_to_update (workspace)
        num_items = 0
        @item = @workspace.items.all

        @workspace.items.each do |item|
            num_items = num_items + item.quantity
        end

        if (num_items > @workspace.max.to_i)
            return false
        else
            return true
        end
    end

    def destroy
        @workspace = Workspace.find(params[:id])
        @workspace.destroy
        redirect_to workspaces_path
    end

    private
        def set_workspace
            @workspace = Workspace.find(params[:id])
        end

        def workspace_params
            params.require(:workspace).permit(:name, :max, :details, :position)
        end
        
        def sort_column
            Workspace.column_names.include?(params[:sort]) ? params[:sort] : "name"
        end
        
        def sort_direction
            %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
        end
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/workspaces/_edit.html.erb
<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel" style="text-align:left;"><strong>Edit Workspace</strong></h4>
    <button type="button" class="close" style="text-align:left;" data-dismiss="modal"><h6>X</h6></button>
</div>

<%= render 'form' %>

app/views/workspaces/_form.html.erb
<%= form_with model: @workspace, local: true do |form| %>
    <div class="modal-body">
        <table>
            <tr>
                <td><%= form.label :name %> </td>
            </tr>
            <tr>
                <td><%= form.text_field :name, placeholder: "Insert workspace name", class:"form-control" %></td>
            </tr>
            <tr>
                <td><%= form.label :max %></td>
            </tr>
            <tr>
                <td><%= form.number_field :max, placeholder: "Insert workspace maximum quantity", class:"form-control" %></td>
            </tr>
            <tr>
                <td><%= form.label :details %></td> 
            </tr>
            <tr>
                <td><%= form.text_area :details, placeholder: "Insert workspace details", class:"form-control" %></td>
            </tr>
        </table>
    </div>
    
    <div class="modal-footer">
        <button class="btn btn-primary">Submit</button>
    </div>

<% end %>

app/views/workspaces/_new.html.erb
<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel" style="text-align:left;"><strong>New Workspace</strong></h4>
    <button type="button" class="close" style="text-align:left;" aria-label= "close" data-dismiss="modal">X</button>
</div>

<%= render 'form' %>

app/views/workspaces/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'edit') %>");
$("#modal-window").modal();

app/views/workspaces/index.html.erb
<%= stylesheet_link_tag "workspace" %>

<p>
  <div class="titleBloc">
    <h1><strong>Workspaces List</strong></h1>
  </div>
</p>

<div class="shadow p-3 mb-5 bg-white rounded">
  <div class="card-body">
    <blockquote class="blockquote">
      <p>Workspace Ordering</p>
      <p class ="blockquote-footer">You can drag and drop the workspace to arrange the order | Please refresh the page after rearranging </footer>
    </blockquote>
    <% if Workspace.count == 0%>
      <p> You have no workspace, please create a new workspace</p>
    <%end%>
    <div data-controller="drag" data-drag-url="/workspaces/:id/move">
      <% @workspaces.order(position: :asc).each do |workspace| %>
        <div data-id="<%= workspace.id %>" class="card card-body mb-4">
          <%= workspace.position %>
          <%= workspace.name %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% if current_user.role == "Admin" %>
  <%= link_to 'Add workspace', new_workspace_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary'}  %>
<% end %>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content"></div>
  </div>
</div>
<br>
<br>

<div class="row row-cols-1 row-cols-md-2">
  <% @workspaces.order(position: :asc).each do |workspace| %>
    <div class="col mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><strong><%= workspace.name %></strong></h5>
          <h6 class="card-subtitle mb-2 text-muted">Maximum : <%= workspace.max %></h6>
          <p class="card-text"><%= workspace.details %></p>
          <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="First group">
              <%= link_to 'Open', workspace_path(workspace), class:"btn btn-warning btn-sm" %>
              <% if current_user.role == "Admin" %>
                <%= link_to 'Edit', edit_workspace_path(workspace), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-outline-primary btn-sm'} %>
                <%= link_to 'Delete', workspace_path(workspace), method: :delete, data: { confirm: 'Are you sure to delete?' }, class:"btn btn-outline-danger btn-sm"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

<%= link_to 'Back to Home Screen', root_path, class:"btn btn-info" %>

app/views/workspaces/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

app/views/workspaces/show.html.erb
<br>
<div class="card border-info mb-3" style="max-width: 18rem;">
  <div class="card-body text-info">
    <h5 div class="card-title"><strong> <%= @workspace.name %> </strong> </h5>
    <p class="card-text"> Maximum: <%= @workspace.max %></p>
    <p class="card-text"> Details: <%= @workspace.details %></p>
  </div>
</div>
<p>
  <% if current_user.role == "Admin" %>
    <%= link_to 'Edit Phase', edit_workspace_path(@workspace), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-dark btn-sm'} %>
    <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
  <% end %>
</p>
<p>
    <h2> <strong>Items</strong> </h2>
</p>

<% if current_user.role == "Admin"%>
  <p>
    <%= link_to 'Add Item', new_workspace_item_path(@workspace), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-sm'}  %>
      <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content"></div>
        </div>
      </div>
  </p>
<% end %>

<table class="table">
  <tr>
      <th><strong>Name</strong>
      <th><strong>Owner</strong>
      <th><strong>Quantity</strong>
      <th><strong>Details</strong>
      <th><strong>Picture</strong>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
  </tr>
  <%= render 'items/item' %>
</table><br><br>


<% if @workspace != Workspace.order(:position).first %>
  <%= link_to 'Previous', workspace_previous_path(@workspace), class:"btn btn-secondary btn-sm" %>
<% end %>

<% if @workspace != Workspace.order(:position).last %>
  <%= link_to 'Next', workspace_next_path(@workspace), class:"btn btn-light btn-sm" %>
<% end %>

<br><br>

<%= link_to 'Back to List of Phases', workspaces_path, class: "btn btn-info"%>