config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'pages/info'

  get '/items/all', to: 'items#index_all'
  get '/items/current', to: 'items#index_current'
  get '/items/finished', to: 'items#index'

  get '/users/list', to: 'home#users'

  resources :workspaces do
    member do
      patch :move
    end
    get 'next', action: :next, controller: 'workspaces'
    get 'previous', action: :previous, controller: 'workspaces'
    resources :items do
      get 'next', action: :next, controller: 'items'
      get 'previous', action: :previous, controller: 'items'
      resources :dues
    end
  end

  root to: 'home#index'

end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :picture, PictureUploader

  belongs_to :workspace
  has_many :dues, dependent: :destroy
  accepts_nested_attributes_for :dues

  #after_create :generate_code
  #def generate_code
  #  self.name = SecureRandom.hex
  #  save
  #end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    helper_method :sort_column, :sort_direction

    def index
        @items = Item.order(sort_column + " " + sort_direction).where(finish: true)
        respond_to do |format|
            format.xlsx {response.headers['Content-Disposition'] = "attachment; filename = Items.xlsx"}
            format.html { render :index }
        end
    end

    def index_all
        @items = Item.all.order(sort_column + " " + sort_direction)
    end

    def index_current
        @items = Item.order(sort_column + " " + sort_direction).where(finish: false)
    end

    def new
        @workspace = Workspace.find(params[:workspace_id])
        @item = @workspace.items.new
        respond_to do |format|
            format.html
            format.js
        end
        @item.dues.build
    end

    def show
        @workspace = Workspace.find(params[:workspace_id])
        @item = @workspace.items.find(params[:id])

        @qrcode = RQRCode::QRCode.new(workspace_item_path)
        
        @svg = @qrcode.as_svg(
            offset: 0,
            color: '000',
            sharp_rendering: 'crispEdges',
            module_size: 6
        )
        
        require 'barby'
        require 'barby/barcode'
        require 'barby/barcode/qr_code'
        require 'barby/outputter/png_outputter'
      
        barcode = Barby::QrCode.new(workspace_item_path, level: :q, size: 5)
        @base64_output = Base64.encode64(barcode.to_png({ xdim: 5 }))
    end


    def create
        @workspace = Workspace.find(params[:workspace_id])
        @item = @workspace.items.new(item_params)
        
        #if the quantity does not exceeds the max capacity
        if @item.quantity + number_of_items(@workspace) <= @workspace.max.to_i
            @item.create(item_params)
            flash[:notice] = "Item successfully created!"
            redirect_to workspace_path(@workspace)
        else
            flash[:alert] = "The number of items exceeds the maximum workspace capacity!"
            redirect_to workspace_path(@workspace)
        end
    end

    def number_of_items(workspace)
        num_items = 0
        @workspace = Workspace.find(params[:workspace_id])
        @item = @workspace.items.all

        #calculates the number of items in each workspace
        @workspace.items.each do |item|
            num_items += item.quantity
        end
        
        #returns the number of items in a workspace
        return num_items
    end


    def next
        @workspace = Workspace.find(params[:workspace_id])
        @item = @workspace.items.find(params[:item_id])

        #checks whether the workspace is the last workspace or not
        if @workspace == Workspace.order(:position).last
            #flashes a notice when the item is finished
            @item.update_attribute(:finish, true)
            flash[:notice] = "Item #{@item.name} is finished!"
            redirect_to workspace_path(@workspace)

        else
            #.next is defined in model workspace.rb
            @nextworkspace = @workspace.next

            #count the number of items in the nextworkspace
            num_items = 0
            @nextworkspace.items.each do |item|
                num_items += item.quantity
            end

            #if the quantity does not exceeds the max capacity
            if @item.quantity + num_items < @nextworkspace.max.to_i
                @item.update_attribute(:workspace_id, @nextworkspace.id)
                flash[:notice] = "This is #{@nextworkspace.name} workspace"
                redirect_to workspace_path(@nextworkspace)
            else
                flash[:alert] = "Exceeds the capacity of #{@nextworkspace.name} workspace"
                redirect_to workspace_path(@workspace)
            end

        end
    end

    def previous
        @workspace = Workspace.find(params[:workspace_id])
        @item = @workspace.items.find(params[:item_id])

        #checks whether the workspace is the first workspace or not
        if @workspace == Workspace.order(:position).first
            flash[:alert] = "This is the first workspace!"
            redirect_to workspace_path(@workspace)

        else
            #.previous is defined in model workspace.rb
            @prevworkspace = @workspace.previous

            #count the number of items in the nextworkspace
            num_items = 0
            @prevworkspace.items.each do |item|
                num_items += item.quantity
            end

            #if the quantity does not exceeds the max capacity
            if @item.quantity + num_items <= @prevworkspace.max.to_i
                @item.update_attribute(:workspace_id, @prevworkspace.id)
                flash[:notice] = "This is #{@prevworkspace.name} workspace"
                redirect_to workspace_path(@prevworkspace)
            else
                flash[:alert] = "Exceeds the capacity of #{@prevworkspace.name} workspace"
                redirect_to workspace_path(@workspace)
            end

        end
    end

    def edit
        @workspace = Workspace.find(params[:workspace_id])
        @item = @workspace.items.find(params[:id])
        respond_to do |format|
            format.html
            format.js
        end
    end

    def update
        @workspace = Workspace.find(params[:workspace_id])
        @item = @workspace.items.find(params[:id])
        
        @item.update(item_params)
        redirect_to workspace_path(@workspace)
    end 

    def destroy
        @workspace = Workspace.find(params[:workspace_id])
        @item = @workspace.items.find(params[:id])
        @item.destroy
        redirect_to workspace_path(@workspace)
    end
            
    private
        def item_params
            params.require(:item).permit(:name, :owner, :quantity, :details, :picture, :dues_attributes => [:id, :name, :duedate])
        end

        def sort_column
            Item.column_names.include?(params[:sort]) ? params[:sort] : "name"
        end
        
        def sort_direction
            %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
        end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_edit.html.erb
<%= form_with(model: [ @workspace, @item ], local: true) do |form| %>

  <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel" style="text-align:left;">Edit Item</h4>
      <button type="button" class="close" style="text-align:left;" data-dismiss="modal"><h3>X</h3></button>
  </div>

  <div class="modal-body">
      <table>  
          <tr>
              <td><%= form.label :name %></td>
              <td><%= form.text_field :name %></td>
          </tr>
          <tr>
              <td><%= form.label :owner %></td>
              <td><%= form.text_field :owner %></td>
          </tr>    
          <tr>
              <td><%= form.label :quantity %></td>
              <td><%= form.number_field :quantity %></td>
          </tr>
          <tr>
              <td><%= form.label :details %></td>
              <td><%= form.text_area :details %></td>
          </tr>
          <tr>
              <td><%= form.label :picture %></td>
              <td><%= form.file_field :picture %></td>
          </tr>
      </table><br>
   
      <h5>Due Dates</h5>
      <table>
        <% Workspace.all.zip(@item.due_ids).each do |w,d| %>
          <tr>
            <td><%= w.name %></td>
            <td>
              <% if !d.blank? %>
                <%= form.fields_for :dues, Due.find(d) do |dd| %>
                  <%= dd.date_field :duedate %>
                <% end %>
              <% else %>
                <%= form.fields_for :dues, Due.new do |dd| %>
                  <%= dd.hidden_field :name, value: w.name, :readonly => true %>
                  <%= dd.date_field :duedate %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
  </div>

  <div class="modal-footer">
    <%= link_to 'Back', workspace_path(@workspace), class:"btn btn-info" %>
    <button class="btn btn-primary">Submit</button>
  </div>

<% end %>

app/views/items/_index.html.erb
<table class="table table-striped">
    <tr>
        <td><strong><%= sortable "name" %></strong></td>
        <td><strong><%= sortable "owner" %></strong></td>
        <td><strong><%= sortable "quantity" %></strong></td>
        <td><strong><%= sortable "details" %></strong></td>
        <td><strong>Workspace</strong></td>
    </tr>
    <% @items.each do |item| %>
        <tr>
            <td><%= item.name %></td>
            <td><%= item.owner %></td>
            <td><%= item.quantity %></td>
            <td><%= item.details %></td>
            <td><%= item.workspace.name %>
        </tr>
    <% end %>
</table>

app/views/items/_item.html.erb
<% @workspace.items.each do |item| %>
    <% if item.finish != true %>
        <tbody class="table table-hover">
        <tr>
            <td><%= item.name %></td>
            <td><%= item.owner %></td>
            <td><%= item.quantity.to_i %></td>
            <td><%= item.details %></td>
            <td><%= image_tag(item.picture_url, width: 300) if item.picture.present? %></td>

            <td><%= link_to 'Open', workspace_item_path(item.workspace, item),class:"btn btn-warning btn-sm" %>

            <% if current_user.role == "Admin" %>
                <td><%= link_to 'Edit', edit_workspace_item_path(item.workspace, item), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-sm'}  %>
                    <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content"></div>
                    </div>
                </td>
                <td><%= link_to 'Delete', [item.workspace, item],
                    method: :delete,
                    data: { confirm: 'Are you sure to delete?' } ,class:"btn btn-danger btn-sm"%></td>
        
                <% if @workspace != Workspace.order(:position).last %>
                    <td><%= link_to 'Revert to Previous Phase', workspace_item_previous_path(item.workspace, item),class:"btn btn-dark btn-sm" %></td>    
                    <td><%= link_to 'Move to Next Phase', workspace_item_next_path(item.workspace, item),class:"btn btn-light btn-sm" %></td>
                <% else %>
                    <td><%= link_to 'Revert to Previous Phase', workspace_item_previous_path(item.workspace, item),class:"btn btn-light btn-sm" %></td>
                    <td><%= link_to 'Finish', workspace_item_next_path(item.workspace, item), data: { confirm: 'Are you sure bro?' },class:"btn btn-success btn-sm" %></td>
                <% end %>
            <% end %>
        </tr>
    <% end %>
<% end %>

app/views/items/_new.html.erb
<%= form_with(model: [ @workspace, @workspace.items.build ], local: true) do |form| %>

    <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel" style="text-align:left;">New Item</h4>
        <button type="button" class="close" style="text-align:left;" data-dismiss="modal"><h3X</h3></button>
    </div>

    <div class="modal-body">
        <table>  
            <tr>
                <td><%= form.label :name %></td>
                <td><%= form.text_field :name %></td>
            </tr>
            <tr>
                <td><%= form.label :owner %></td>
                <td><%= form.text_field :owner %></td>
            </tr>    
            <tr>
                <td><%= form.label :quantity %></td>
                <td><%= form.number_field :quantity %></td>
            </tr>
            <tr>
                <td><%= form.label :details %></td>
                <td><%= form.text_area :details %></td>
            </tr>
            <tr>
                <td><%= form.label :picture %></td>
                <td><%= form.file_field :picture %></td>
            </tr>
        </table><br>
     
        <h5>Due Dates</h5>
        <table>
            <% Workspace.all.each do |workspace| %>
                <tr>
                    <%= form.fields_for :dues, Due.new do |d| %>
                        <td><%= workspace.name %></td>
                        <td><%= d.hidden_field :name, value: workspace.name, :readonly => true %></td>
                        <td><%= d.date_field :duedate %></td>
                    <% end %>
                </tr>
            <% end %>
        </table>
    </div>
  
    <div class="modal-footer">
        <%= link_to 'Back', workspace_path(@workspace), class:"btn btn-info" %>
        <button class="btn btn-primary">Submit</button>
    </div>
    
<% end %>

app/views/items/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'edit') %>");
$("#modal-window").modal();

app/views/items/index.html.erb
<br>
<div class="titleBloc">
    <h2> <strong> List of Finished Items </strong> </h2>
</div>

<%= link_to 'All Items', items_all_path, class:"btn btn-secondary btn-sm" %>
<%= link_to 'Current Items', items_current_path, class:"btn btn-secondary btn-sm" %>
<%= link_to 'Finished Items', items_finished_path,class:"btn btn-primary btn-sm" %>
<br>
<br>

<%= render 'index' %><br>
<%= link_to 'Download Finished Items', items_finished_path(format: :xlsx), class:"btn btn-info"  %>

app/views/items/index_all.html.erb
<br>
<div class="titleBloc">
    <h2> <strong> List of All Items </strong> </h2>
</div>

<%= link_to 'All Items', items_all_path, class:"btn btn-primary btn-sm" %>
<%= link_to 'Current Items', items_current_path, class:"btn btn-secondary btn-sm" %>
<%= link_to 'Finished Items', items_finished_path,class:"btn btn-secondary btn-sm" %>

<br>
<br>

<%= render 'index' %><br>
<%= link_to 'Download Finished Items', items_finished_path(format: :xlsx), class:"btn btn-info" %>

app/views/items/index_current.html.erb
<br>
<div class="titleBloc">
    <h2> <strong> List of Current Items </strong> </h2>
</div>

<%= link_to 'All Items', items_all_path, class:"btn btn-secondary btn-sm" %>
<%= link_to 'Current Items', items_current_path, class:"btn btn-primary btn-sm" %>
<%= link_to 'Finished Items', items_finished_path,class:"btn btn-secondary btn-sm" %>
<br>
<br>

<%= render 'index' %><br>
<%= link_to 'Download Finished Items', items_finished_path(format: :xlsx), class:"btn btn-info" %>

app/views/items/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

app/views/items/show.html.erb
<br>
<div class="row">
    <div class="col-sm-4">
        <div class="card" style="width: 20rem">
            <div class="card-header">
                <h3>Item Information</h3>
            </div>
            <div class="card-body">
                <p>
                    <strong>Item name:</strong>
                    <%= @item.name %>
                </p>
                <p>
                    <strong>Owner:</strong>
                    <%= @item.owner %>
                </p>
                <p>
                    <strong>Quantity:</strong>
                    <%= @item.quantity.to_i %>
                </p>
                <p>
                    <strong>Details:</strong>    
                    <%= @item.details %>
                </p>

                <p>Image:</p>
                <p><% if !@item.picture.present? %> No Image Uploaded <% end %></p>
                <p><%= image_tag(item.picture_url, width: 300) if @item.picture.present? %></p>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card" style="width: 18rem">
            <div class="card-header">
                <h3>Due Dates</h3>
            </div>
            <div class="card-body">
                <table class="table">
                    <% @item.dues.each do |d| %>
                        <tr>
                            <td><%= d.name %></td>
                            <td><%= d.duedate %></td>
                        </tr>
                    <% end %>
                </table>
            </div>
        </div>
    </div>                                                                                     
    <div class="col-sm-4">
        <div class="card" style="width: 18rem">
            <div class="card-header">
                <h3>QR Code</h3>
            </div>
            <div class="card-body">
                <%= image_tag ("data:image/png;base64,#{@base64_output}") %>
            </div>
        </div>
    </div>
</div>
<br>
<div class="row"> 
    <div class="col-sm-4">
        <div class="card" style="width: 18rem">
            <div class="card-header">
                <h3>Item Actions</h3>
            </div>
            <div class="card-body">
                <% if current_user.role == "Admin" %>
                    <p><%= link_to 'Edit Item', edit_workspace_item_path(@item.workspace, @item), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-sm'} %>
                    <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content"></div>
                        </div>
                    </div>
                    </p>
                    <p><%= link_to 'Delete Item', [@workspace, @item], method: :delete,
                        data: { confirm: 'Are you sure to delete?' } ,class:"btn btn-sm btn-danger"%></p>
                <% end %>
                <p><%= link_to 'Back to List of Items', workspace_path(@workspace),class:"btn btn-sm btn-info" %></p>
            </div>
        </div>
    </div> 
</div>